CACHE_DIR ??= "${TOPDIR}"

BB_GENERATE_MIRROR_TARBALLS = "1"
BB_GIT_SHALLOW ?= "1"
BB_GIT_SHALLOW_DEPTH ?= "1"

DL_DIR = "${CACHE_DIR}/downloads"
SSTATE_DIR = "${CACHE_DIR}/sstate-cache"
CCACHE_TOP_DIR = "${CACHE_DIR}/ccache"

INHERIT += "ccache"
INHERIT += "rm_work"

CCACHE_DISABLE:pn-libgsthailo = "1"

HAILO_PACKAGE_FEED_URIS = "https://solidrun-packages.com/hailo/meta-solidrun-arm-hailo/"
HAILO_PACKAGE_FEED_BASE_PATHS = "ipk"
HAILO_PACKAGE_FEED_ARCHS = "all armv8a"
