CACHE_DIR ??= "${TOPDIR}"
CI_MIRROR ??= ""

BB_GENERATE_MIRROR_TARBALLS = "1"
BB_GIT_SHALLOW ?= "1"
BB_GIT_SHALLOW_DEPTH ?= "1"

DL_DIR = "${CACHE_DIR}/downloads"
SSTATE_DIR = "${CACHE_DIR}/sstate-cache"
CCACHE_TOP_DIR = "${CACHE_DIR}/ccache"

INHERIT += "ccache"
INHERIT += "rm_work"

SOURCE_MIRROR_URL ?= "${CI_MIRROR}"
INHERIT += "own-mirrors"

CCACHE_DISABLE:pn-libgsthailo = "1"
