# flags
LICENSE_FLAGS_ACCEPTED:append = " commercial"

DSP_COMPILATION_MODE = "release"
ADD_GSTREAMER_TO_IMAGE = "true"

CORE_IMAGE_EXTRA_INSTALL:append = " x264 gstreamer1.0-plugins-ugly"
PACKAGECONFIG:append:pn-gstreamer1.0-plugins-ugly = " x264"

CORE_IMAGE_EXTRA_INSTALL:append = " libdrm libdrm-kms libdrm-tests fb-test"
CORE_IMAGE_EXTRA_INSTALL:append = " python3-pillow python3-numpy"
PACKAGECONFIG:append:pn-gstreamer1.0-plugins-bad = " kms"

DISTRO_FEATURES:append = " hailo-core"
DISTRO_FEATURES:append = " hailo-dev-pkg"
CORE_IMAGE_EXTRA_INSTALL:append = " packagegroup-hailo-tappas-dev-pkg"
CORE_IMAGE_EXTRA_INSTALL:append = " pyhailort"
