# Image settings
CORE_IMAGE_EXTRA_INSTALL:append = " bmap-tools"
IMAGE_FSTYPES:append = " wic.bmap wic.zst"

CORE_IMAGE_EXTRA_INSTALL:append = " bluez5"
CORE_IMAGE_EXTRA_INSTALL:append = " connman connman-client connman-static"
CORE_IMAGE_EXTRA_INSTALL:append = " wget ca-certificates"

IMAGE_FEATURES:append = " package-management"