require conf/machine/include/hailo15-base.inc
require conf/machine/include/hailo-vpu-base.inc

MACHINEOVERRIDES =. "hailo15-solidrun:"
UBOOT_MACHINE = "hailo15_solidrun_defconfig"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += "kernel-module-brcmfmac \
                                        kernel-module-brcmutil \
                                        kernel-module-hci-uart \
                                        wireless-regdb-static \
                                        linux-firmware-bcm43455 \
"
MACHINE_FEATURES += "bluetooth wifi"

KERNEL_OVERLAYS:hailo15-solidrun = " \
    ${LINUX_YOCTO_HAILO_BOARD_VENDOR}/hailo15-sr-som-v1-overlay.dtbo \
"

INITRAMFS_IMAGE = "core-image-flashing-ramdisk"

WKS_FILE ?= "hailo15-solidrun.wks"
# Hailo v1.12 dropped wic support upstream and with it these dependencies.
# wic copies these into the boot partition (IMAGE_BOOT_FILES), so they must be built and deployed first.
WKS_FILE_DEPENDS:append = " swupdate-image linux-yocto-hailo u-boot-tfa-image"
