require conf/machine/include/hailo15-base.inc
require conf/machine/include/hailo-vpu-base.inc

MACHINEOVERRIDES =. "hailo15-solidrun:"
UBOOT_MACHINE = "hailo15_solidrun_defconfig"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += "kernel-module-brcmfmac \
                                        kernel-module-brcmutil \
                                        kernel-module-hci-uart \
                                        wireless-regdb-static \
                                        linux-firmware-bcm43455 \
"
MACHINE_FEATURES += "bluetooth wifi"

KERNEL_OVERLAYS:hailo15-solidrun = " \
    ${LINUX_YOCTO_HAILO_BOARD_VENDOR}/hailo15-sr-som-v1-overlay.dtbo \
"

INITRAMFS_IMAGE = "core-image-flashing-ramdisk"
